config/routes.rb
Reclamecin::Application.routes.draw do
  get "login/new"

  post "login/create"

  get "login/destroy"

  get "cadastrar_reprovacao/create"
  match 'cadastrar_reprovacao/:id' => 'cadastrar_reprovacao#create'

  get "cadastrar_aprovacao/create"
  match 'cadastrar_aprovacao/:id' => 'cadastrar_aprovacao#create'

  resources :opiniaos

  resources :reclamacaos

  resources :usuarios

  root :to => 'login#new'

end

app/models/reclamacao.rb
class Reclamacao < ActiveRecord::Base
  belongs_to :usuario
  has_many :opiniaos
  attr_accessible :descricao , :titulo, :usuario_id
  validates :descricao, presence: true
  validates :titulo, presence: true
end

app/controllers/reclamacaos_controller.rb
class ReclamacaosController < ApplicationController
  # GET /reclamacaos
  # GET /reclamacaos.json
  skip_before_filter :logado
  def index
  
    @reclamacaos = Reclamacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reclamacaos }
    end
  end

  # GET /reclamacaos/1
  # GET /reclamacaos/1.json
  def show
	
    @reclamacao = Reclamacao.find(params[:id])
    @aprova = Opiniao.where(:reclamacao_id => @reclamacao.id, :gostou => true).count
    @aprovados = Opiniao.where(:reclamacao_id => @reclamacao.id, :gostou => true)
    @reprova = Opiniao.where(:reclamacao_id => @reclamacao.id, :nao_gostou => true).count
    @reprovados = Opiniao.where(:reclamacao_id => @reclamacao.id, :nao_gostou => true)
    @opinioes = Opiniao.where(:reclamacao_id => @reclamacao.id)

    respond_to do |format|
      format.html # show.html.erb
      #format.json { render json: @reclamacao.to_json(:include => :opiniaos) }
      format.json { render json: [@reclamacao.to_json, :aprovados => @aprovados.to_json(:only => [:created_at, :usuario_id, :updated_at]) , :reprovados => @reprovados.to_json(:only => [:created_at, :usuario_id, :updated_at])] }
    end
  end

  # GET /reclamacaos/new
  # GET /reclamacaos/new.json
  def new
    @reclamacao = Reclamacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reclamacao }
    end
  end

  # GET /reclamacaos/1/edit
  def edit
    @reclamacao = Reclamacao.find(params[:id])
  end

  # POST /reclamacaos
  # POST /reclamacaos.json
  def create
    @reclamacao = Reclamacao.new(params[:reclamacao])

    respond_to do |format|
      if @reclamacao.save
        format.html { redirect_to @reclamacao, notice: 'Reclamacao was successfully created.' }
        format.json { render json: @reclamacao, status: :created, location: @reclamacao }
      else
        format.html { render action: "new" }
        format.json { render json: @reclamacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reclamacaos/1
  # PUT /reclamacaos/1.json
  def update
    @reclamacao = Reclamacao.find(params[:id])

    respond_to do |format|
      if @reclamacao.update_attributes(params[:reclamacao])
        format.html { redirect_to @reclamacao, notice: 'Reclamacao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reclamacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reclamacaos/1
  # DELETE /reclamacaos/1.json
  def destroy
    @reclamacao = Reclamacao.find(params[:id])
    @reclamacao.destroy

    respond_to do |format|
      format.html { redirect_to reclamacaos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reclamacaos_helper.rb
module ReclamacaosHelper
end

app/views/reclamacaos/_form.html.erb
<%= form_for(@reclamacao) do |f| %>
  <% if @reclamacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reclamacao.errors.count, "error") %> prohibited this reclamacao from being saved:</h2>

      <ul>
      <% @reclamacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= f.label :usuario %><br />
    <%#= f.collection_select(:usuario_id, Usuario.all, :id, :login, {include_blank: true}) %>
    <%= f.hidden_field :usuario_id, :value => session[:sis_logon].id %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reclamacaos/edit.html.erb
<h1>Editing reclamacao</h1>

<%= render 'form' %>

<%= link_to 'Show', @reclamacao %> |
<%= link_to 'Back', reclamacaos_path %>

app/views/reclamacaos/index.html.erb
<h1>Listing reclamacaos</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Titulo</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reclamacaos.each do |reclamacao| %>
  <tr>
    <td><%= reclamacao.usuario %></td>
    <td><%= reclamacao.titulo %></td>
    <td><%= reclamacao.descricao %></td>
    <td><%= link_to 'Show', reclamacao %></td>
    <td><%= link_to 'Edit', edit_reclamacao_path(reclamacao) %></td>
    <td><%= link_to 'Destroy', reclamacao, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reclamacao', new_reclamacao_path %>

app/views/reclamacaos/new.html.erb
<h1>New reclamacao</h1>

<%= render 'form' %>

<%= link_to 'Back', reclamacaos_path %>

app/views/reclamacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @reclamacao.usuario %>
</p>

<p>
  <b>Titulo:</b>
  <%= @reclamacao.titulo %>
</p>

<p>
  <b>Descricao:</b>
  <%= @reclamacao.descricao %>
</p>

<p>
<b style="color:#006600"><%= @aprova %></b> <%= link_to 'Concorda', '/cadastrar_aprovacao/' + @reclamacao.id.to_s %> |
  <b style="color:#FF0000"><%= @reprova %></b> <%= link_to 'Discorda', '/cadastrar_reprovacao/' + @reclamacao.id.to_s %>
</p>

<%= link_to 'Edit', edit_reclamacao_path(@reclamacao) %> |
<%= link_to 'Back', reclamacaos_path %>