config/routes.rb
Reclamecin::Application.routes.draw do
  get "login/new"

  post "login/create"

  get "login/destroy"

  get "cadastrar_reprovacao/create"
  match 'cadastrar_reprovacao/:id' => 'cadastrar_reprovacao#create'

  get "cadastrar_aprovacao/create"
  match 'cadastrar_aprovacao/:id' => 'cadastrar_aprovacao#create'

  resources :opiniaos

  resources :reclamacaos

  resources :usuarios

  root :to => 'login#new'

end

app/models/opiniao.rb
class Opiniao < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :reclamacao
  attr_accessible :gostou, :nao_gostou, :usuario_id, :reclamacao_id
end

app/controllers/opiniaos_controller.rb
class OpiniaosController < ApplicationController
  # GET /opiniaos
  # GET /opiniaos.json
  def index
    @opiniaos = Opiniao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @opiniaos }
    end
  end

  # GET /opiniaos/1
  # GET /opiniaos/1.json
  def show
    @opiniao = Opiniao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @opiniao }
    end
  end

  # GET /opiniaos/new
  # GET /opiniaos/new.json
  def new
    @opiniao = Opiniao.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @opiniao }
    end
  end

  # GET /opiniaos/1/edit
  def edit
    @opiniao = Opiniao.find(params[:id])
  end

  # POST /opiniaos
  # POST /opiniaos.json
  def create
    @opiniao = Opiniao.new(params[:opiniao])

    respond_to do |format|
      if @opiniao.save
        format.html { redirect_to @opiniao, notice: 'Opiniao was successfully created.' }
        format.json { render json: @opiniao, status: :created, location: @opiniao }
      else
        format.html { render action: "new" }
        format.json { render json: @opiniao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /opiniaos/1
  # PUT /opiniaos/1.json
  def update
    @opiniao = Opiniao.find(params[:id])

    respond_to do |format|
      if @opiniao.update_attributes(params[:opiniao])
        format.html { redirect_to @opiniao, notice: 'Opiniao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @opiniao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opiniaos/1
  # DELETE /opiniaos/1.json
  def destroy
    @opiniao = Opiniao.find(params[:id])
    @opiniao.destroy

    respond_to do |format|
      format.html { redirect_to opiniaos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/opiniaos_helper.rb
module OpiniaosHelper
end

app/views/opiniaos/_form.html.erb
<%= form_for(@opiniao) do |f| %>
  <% if @opiniao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@opiniao.errors.count, "error") %> prohibited this opiniao from being saved:</h2>

      <ul>
      <% @opiniao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %><br />
    <%= f.text_field :usuario %>
  </div>
  <div class="field">
    <%= f.label :gostou %><br />
    <%= f.check_box :gostou %>
  </div>
  <div class="field">
    <%= f.label :nao_gostou %><br />
    <%= f.check_box :nao_gostou %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/opiniaos/edit.html.erb
<h1>Editing opiniao</h1>

<%= render 'form' %>

<%= link_to 'Show', @opiniao %> |
<%= link_to 'Back', opiniaos_path %>

app/views/opiniaos/index.html.erb
<h1>Listing opiniaos</h1>

<table>
  <tr>
    <th>Usuario</th>
    <th>Gostou</th>
    <th>Nao gostou</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @opiniaos.each do |opiniao| %>
  <tr>
    <td><%= opiniao.usuario %></td>
    <td><%= opiniao.gostou %></td>
    <td><%= opiniao.nao_gostou %></td>
    <td><%= link_to 'Show', opiniao %></td>
    <td><%= link_to 'Edit', edit_opiniao_path(opiniao) %></td>
    <td><%= link_to 'Destroy', opiniao, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Opiniao', new_opiniao_path %>

app/views/opiniaos/new.html.erb
<h1>New opiniao</h1>

<%= render 'form' %>

<%= link_to 'Back', opiniaos_path %>

app/views/opiniaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @opiniao.usuario %>
</p>

<p>
  <b>Gostou:</b>
  <%= @opiniao.gostou %>
</p>

<p>
  <b>Nao gostou:</b>
  <%= @opiniao.nao_gostou %>
</p>


<%= link_to 'Edit', edit_opiniao_path(@opiniao) %> |
<%= link_to 'Back', opiniaos_path %>