config/routes.rb
Reclamecin::Application.routes.draw do
  get "login/new"

  post "login/create"

  get "login/destroy"

  get "cadastrar_reprovacao/create"
  match 'cadastrar_reprovacao/:id' => 'cadastrar_reprovacao#create'

  get "cadastrar_aprovacao/create"
  match 'cadastrar_aprovacao/:id' => 'cadastrar_aprovacao#create'

  resources :opiniaos

  resources :reclamacaos

  resources :usuarios

  root :to => 'login#new'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  has_many :opiniaos
  has_many :reclamacaos
  attr_accessible :email, :login, :senha
  def to_s
    login
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  skip_before_filter :logado
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :senha %><br />
    <%= f.text_field :senha %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <tr>
    <th>Login</th>
    <th>Senha</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.login %></td>
    <td><%= usuario.senha %></td>
    <td><%= usuario.email %></td>
    <td><%= link_to 'Show', usuario %></td>
    <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Destroy', usuario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Login:</b>
  <%= @usuario.login %>
</p>

<p>
  <b>Senha:</b>
  <%= @usuario.senha %>
</p>

<p>
  <b>Email:</b>
  <%= @usuario.email %>
</p>


<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>